name: pub_chem
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.1
  go_router: ^17.1.0
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  freezed_annotation: ^3.1.0
  freezed: ^3.2.5
  build_runner: ^2.10.2
  equatable: ^2.0.7
  dio: ^5.9.1
  package_info_plus: ^8.1.1
  shimmer: ^3.0.0
  logging: ^1.3.0



dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  json_serializable: ^6.8.0
  very_good_analysis: ^10.0.0

flutter:
  generate: true
  uses-material-design: true

assets:
  - assets/app_icon.png

